version: "3.7"

services:

  be:
    image: jscdroiddev/docker-nodejs-mariadb-be:dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: my_user
      DB_PASSWORD: ${SERVER_DB_PASSWORD}
      DB_NAME: my_app
      BACK_END_API_PORT: 3001
      FRONT_END_API_HOST: my-server.tld
      FRONT_END_API_PORT: "80, 443, 3000"

  fe:
    image: jscdroiddev/docker-nodejs-mariadb-fe:dev
    restart: unless-stopped
    ports:
      - "3000:80"
  
  db:
    image: mariadb:latest
    restart: unless-stopped    
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_user
      MYSQL_PASSWORD: ${SERVER_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: "/opt/dnm/db/my_data"
        target: "/var/lib/mysql"
      - type: bind
        source: "/opt/dnm/db/updates"
        target: "/home"

volumes:
  db: