version: "3.7"

services:

  be:
    image: jscdroiddev/full-stack-app-be:JSCVERSION
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: my_user
      DB_PASSWORD: ${SERVER_DB_PASSWORD}
      DB_NAME: my_app
      BACK_END_API_PORT: 3001
      FRONT_END_API_HOST: rochefolle.org
      FRONT_END_API_PORT: none
      FRONT_END_API_SCHEME: https

  fe:
    image: jscdroiddev/full-stack-app-fe:JSCVERSION
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
  
  db:
    image: mariadb:latest
    restart: unless-stopped    
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_user
      MYSQL_PASSWORD: ${SERVER_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: "/opt/fsa/db/my_data"
        target: "/var/lib/mysql"
      - type: bind
        source: "/opt/fsa/db/updates"
        target: "/home"

volumes:
  db: