version: "3.7"

services:

  be:
    build:
      context: be/
      target: development
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./be/src
        target: /opt/dnm/src
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: some_great_password
      DB_NAME: my_app
      BACK_END_API_PORT: 3001
      FRONT_END_API_HOST: localhost
      FRONT_END_API_PORT: 3000
      FRONT_END_API_SCHEME: http

  fe:
    build:
      context: fe/
      target: development
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./fe/src
        target: /opt/dnm/src
      - type: bind
        source: ./fe/public
        target: /opt/dnm/public
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACK_END_API_HOST: localhost
      REACT_APP_BACK_END_API_PORT: 3001
    
  db:
    build:
      context: db/
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: some_great_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3306:3306"
  
volumes:
  be:
  fe:
  db: